import type { ReactNode } from "react";

import type { Metadata } from "next";
import localFont from "next/font/local";

import { ThemeProvider } from "next-themes";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import "@/app/globals.css";
import { Toaster } from "@/registry/new-york-v4/ui/sonner";
import Providers from "./provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#F6F6F6] text-foreground overscroll-none antialiased`}
      >
        <Providers>
          <ThemeProvider attribute="class">
            {/* <NavigationBar /> */}
            <main className="container mx-auto px-4 py-6 md:px-6 lg:px-8">
              {children}
            </main>
            <Toaster />
          </ThemeProvider>
        </Providers>
        {/* <MenuBottom /> */}
      </body>
    </html>
  );
};

export default Layout;
